version: "3.3"

services:
  app:
    build:
      context: .
    container_name: Azia
    env_file:
      - .env
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - "3333:3333"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgresproject
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $PG_USER
      interval: 3s
      timeout: 4s
      retries: 5

    ports:
      - "5432:5432"
volumes:
  postgres:
    external: true
